### ISSUE TITLE
Import UI components figma?

### ISSUE THREAD

**Issue by nunoluanova** [MarsX-dev/floatui#1]
Hello, the project is amazing.
Congratulations to all those responsible.

Sorry if my question is amateur, but I would like to know if it is possible to import the design components in figma and when adjusting, color, titles, block, spacing, the update would be noticed in the online model.

I would like to use the project to assemble internal frameworks before the complete modeling of a page.

thank you for your attention

**Comment by sidiDev** [comment]
Hi @nunoluanova good question. Sorry but the Figma version isn't available for public, but answering to your question, No I think the update won't be noticed in online mode, because when you import it, you will have a new version of it, and you can make it public or private, and the update will be noticed only in your copy, not our.

Do you have any other question?
