### ISSUE TITLE
change in modal

### ISSUE THREAD

**Issue by karapy** [MarsX-dev/floatui#41]
as I remember a couple of times I used Modal component,
there was not such a thing like:
import * as Dialog from "@radix-ui/react-dialog";

advantage o using floatui for me was not using anything but tailwindcss itself

**Comment by sidiDev** [comment]
@karapy Hey there, hope you’re doing well,
As you know we use only Headless UI like RadixUI, which is great if you want accessible components,
Plus there are so many things you don’t need to add in your component, like the logic provided by Radix, because if you wanna write it inside your component from scratch, will take time, and you’ll end up with a lot of code ...etc.
and if you want the HTML only, you can copy it from the browser directly,
Check out the features of radix here: [https://www.radix-ui.com/primitives/docs/overview/introduction](https://www.radix-ui.com/primitives/docs/overview/introduction)
